fixed bootstrap und configure. solle wieder durchkompilieren

diff --git a/microcontroller/src-host/bootstrap b/microcontroller/src-host/bootstrap
--- a/microcontroller/src-host/bootstrap
+++ b/microcontroller/src-host/bootstrap
@@ -28,6 +28,13 @@ DIE=0
   NO_AUTOMAKE=yes
 }
 
+(libtoolize --version) < /dev/null > /dev/null 2>&1 || {
+  echo
+  echo "**Error**: You must have Libtoolize' installed"
+  DIE=1
+  NO_LIBTOOLIZE=yes
+}
+
 # if no automake, don't bother testing for aclocal
 test -n "$NO_AUTOMAKE" || (aclocal --version) < /dev/null > /dev/null 2>&1 || {
   echo
@@ -41,7 +48,8 @@ if test "$DIE" -eq 1; then
   exit 1
 fi
 
-
+echo "Libtoolize... " &&
+libtoolize &&
 echo "Running aclocal..." && 
 aclocal &&
 echo "Running autoheader..." &&
